<?xml version="1.0"?>
<robot name="hrc_simulation" xmlns:xacro="https://ros.org/wiki/xacro">

    <xacro:arg name="robot" default="hrc_simulation" />      <!-- can be "mobipick-hb" or "mobipick-os" -->
    <xacro:property name="robot" value="$(arg robot)" />  <!-- necessary because args cannot be accessed inside ${} expressions -->
    <xacro:property name="prefix" value="" />
    <!-- workbench-->
    <xacro:include filename="$(find vention_conveyor_description)/urdf/workbench_table.urdf.xacro" />

    <link name="world" />

    <!--joint that connects world and workbench-->
    <joint name="world_joint" type="fixed">
        <parent link="world" />
        <child link="workbench_base" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>


    <xacro:workbench_table prefix="" />

    <!-- ur5e -->
    <xacro:include filename="$(find ur_description)/urdf/inc/ur5e_macro.xacro" />

    <xacro:arg name="transmission_hw_interface" default="hardware_interface/PositionJointInterface" />
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur5e/joint_limits.yaml"/>
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur5e/default_kinematics.yaml"/>
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur5e/default_kinematics.yaml"/>
    <xacro:arg name="visual_params" default="$(find ur_description)/config/ur5e/visual_parameters.yaml"/>


    <xacro:ur5e_robot prefix="${prefix}"
    transmission_hw_interface="$(arg transmission_hw_interface)"
    joint_limits_parameters_file="$(arg joint_limit_params)"
    kinematics_parameters_file="$(arg kinematics_params)" 
    visual_parameters_file="$(arg visual_params)"/>

    
    <!--joint that connects workbench and ur5e-->
    <joint name="attachment_joint" type="fixed">
        <parent link="workbench_mount" />
        <child link="${prefix}base_link" />
        <origin xyz="0.0 0.0 0.00" rpy="0 0.0 3.14159" />
    </joint>



    <!-- ############## FT SENSOR ############### -->
    <!-- gripper coupling (ISO 9409-1-50-4-M / Robotiq AGC-CPL-062-002_20171219) -->
    <xacro:property name="coupling_radius" value="0.0375" />
    <xacro:property name="coupling_outer_length" value="0.014" />
    <xacro:property name="coupling_inner_length" value="0.008" />
    <xacro:property name="coupling_mass" value="0.100" />

    <xacro:include filename="$(find robotiq_ft_sensor)/urdf/robotiq_ft300.urdf.xacro" />

    <xacro:robotiq_ft300 parent="${prefix}tool0" prefix="${prefix}">
        <origin xyz="0 0 ${-coupling_inner_length / 2}" rpy="0 0 ${-pi/2}" />
    </xacro:robotiq_ft300>


    <!-- ############### CAMERA MOUNT ################ -->
    <xacro:include filename="$(find azure_kinect_ros_driver)/urdf/camera_mount.urdf.xacro" />

    <xacro:azure_camera_mount prefix="${prefix}" parent="${prefix}robotiq_ft_frame_id" >
        <origin xyz="0.05 0.0375 0.04" rpy="${pi/2} ${pi} 0"/>
    </xacro:azure_camera_mount>

    <!-- ############### CAMERA ################ -->
    
    <xacro:include filename="$(find azure_kinect_ros_driver)/urdf/azure_kinect_1.urdf.xacro" />

    <xacro:azure_kinect_1 prefix="${prefix}" parent="${prefix}world_camera" >
        <origin xyz="0.5 0 1" rpy="0 ${pi/2} 0"/>
    </xacro:azure_kinect_1>
    

    <xacro:include filename="$(find azure_kinect_ros_driver)/urdf/azure_kinect.urdf.xacro" />

    <xacro:azure_kinect prefix="" parent="${prefix}camera_link" >
        <origin xyz="0.05 -0.04 0.106" rpy="0 0 ${-pi/2}"/>
    </xacro:azure_kinect>
    <!-- Define camera_base_optical as a child, not a root link -->
    <link name="camera_base_optical" >    
    </link>
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_base"/>
        <child link="camera_base_optical"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>    

    <!-- Attach the camera sensor to the camera base -->
    
    <gazebo reference="camera_base">
        <material>Gazebo/Black</material>

        <sensor name="camera" type="depth">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_base_optical</frame_name>
                <cameraName>azure_kinect_camera</cameraName>
                <min_depth>0.1</min_depth>
                <max_depth>10</max_depth>
            </plugin>
        </sensor>
    </gazebo>         
    
    <!-- ############### GRIPPER ################ -->
    
    <xacro:include filename="$(find robotiq_85_description)/urdf/robotiq_85_gripper.urdf.xacro" />

    <joint name="${prefix}robotiq_coupler_joint" type="fixed">
        <parent link="${prefix}tool_link"/>
        <child link="${prefix}gripper_coupler_link"/>
        <origin xyz="0.05 0.025 0.04" rpy="${-pi/2} 0 0" />
    </joint>
    
    <link name="${prefix}gripper_coupler_link">
        <visual>
            <geometry>
                <cylinder radius="0.04" length="0.017"/>
            </geometry>
            <material name="black">
                <color rgba="1 1 1 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.04" length="0.017"/>
            </geometry>
        </collision>
    </link>

    <xacro:robotiq_85_gripper prefix="${prefix}" parent="${prefix}gripper_coupler_link" >
        <origin xyz="0 0 -0.008" rpy="0 ${pi/2} ${-pi/2}" />
    </xacro:robotiq_85_gripper>
    
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"> 
            <robotNamespace>/</robotNamespace>
        </plugin> 
    </gazebo>

</robot>
